apiVersion: v1
kind: Service
metadata:
  name: iot-registry
  labels:
    app: registry
    tier: iot-registry

spec:
  ports:
    # the port that this service should serve on
  - port: 5000
    targetPort: 5000
  selector:
    app: registry
    tier: iot-registry
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iot-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
        tier: iot-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
          - containerPort: 5000
          env:
          - name: GET_HOSTS_FROM
            value: dns
          volumeMounts:
          - name: regdata-storage
            mountPath: /var/lib/registry
          - name: regconf-storage
            mountPath: /etc/docker/registry
            readOnly: true
          - name: regcert-storage
            mountPath: /ssl
            readOnly: true
      volumes:
        - name: regdata-storage
          gcePersistentDisk:
            pdName: disk-iot-data
            fsType: ext4
        - name: regconf-storage
          gcePersistentDisk:
            pdName: disk-iot-data
            fsType: ext4
        - name: regcert-storage
          gcePersistentDisk:
             pdName: disk-iot-data
             fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: iot-dockerauth
  labels:
    app: dockerauth
    tier: iot-dockerauth
spec:
  ports:
    # the port that this service should serve on
  - port: 5001
    targetPort: 5001
  type: LoadBalancer
  selector:
    app: dockerauth
    tier: iot-dockerauth
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iot-dockerauth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dockerauth
        tier: iot-dockerauth
    spec:
      containers:
      - name: dockerauth
        # image: peihsinsu/simpleweb:x86
        image: zyfdedh/docker_auth
        args: ["--v=2", "--alsologtostderr", "/config/auth_config.yml"]
        ports:
        - containerPort: 5001
        env:
        - name: AUTH_API_ENDPOINT
          value: iot-server:3000
        - name: GET_HOSTS_FROM
          value: dns
        volumeMounts:
          - name: authconf-storage
            mountPath: /config
            readOnly: true
          - name: authcert-storage
            mountPath: /ssl
            readOnly: true
      volumes:
        - name: authconf-storage
          gcePersistentDisk:
            pdName: disk-iot-data
            fsType: ext4
        - name: authcert-storage
          gcePersistentDisk:
            pdName: disk-iot-data
            fsType: ext4
