apiVersion: v1
kind: Service
metadata:
  name: iot-registry
  labels:
    app: registry
    tier: iot-registry

spec:
  ports:
    # the port that this service should serve on
  - port: 5000
    targetPort: 5000
  type: LoadBalancer
  selector:
    app: registry
    tier: iot-registry
  sessionAffinity: ClientIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: iot-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: registry
        tier: iot-registry
    spec:
      containers:
        - name: registry
          image: registry:2
          ports:
          - containerPort: 5000
          env:
          - name: GET_HOSTS_FROM
            value: dns
          volumeMounts:
          - name: regdata-storage
            mountPath: /var/lib/registry
          - name: regconf-storage
            mountPath: /etc/docker/registry
            readOnly: true
          - name: regcert-storage
            mountPath: /ssl
            readOnly: true
      volumes:
        - name: regdata-storage
          hostPath:
            path: /tmp/volumes/iot-registry/data
        - name: regconf-storage
          hostPath:
            path: /tmp/volumes/iot-registry/conf
        - name: regcert-storage
          hostPath:
            path: /tmp/volumes/iot-registry/ssl
